---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo_db
    tier: mongo-database
spec:
  selector:
    matchLabels:
      app: mongo_db
  template:
    metadata:
      labels:
        app: mongo_db
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.6
        envFrom:
          - configMapRef:
              name: mongo-configmap
          - secretRef:
              name: mongo-secret
        ports:
        - containerPort: 27017
          name: mp3-mongo
        volumeMounts:
          - mountPath: "/var/lib/mongo/"
            name: mongo-pv-claim
          
          - name: mongodb-data
            mountPath: /data
      volumes:
        - name: mongo-pv-claim
          hostPath:
            path: "/mnt/mongo"
        
        - name: mongodb-data
          hostPath:
            path: /mnt/mongodata
            type: DirectoryOrCreate
          # persistentVolumeClaim:
          #   claimName: mongo-pv-claim
        # - name: mongo-db-data
        #   persistentVolumeClaim:
        #     claimName: mongo-db-data

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo_db
spec:
  selector:
    app: mongo_db
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  type: ClusterIP
