---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db
    tier: database
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: MYSQL_ROOT_PASSWORD
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "600m"
          ports:
            - containerPort: 3306
              name: mp3-mysql
          volumeMounts:
            #  inside container
            - mountPath: "/docker-entrypoint-initdb.d/"
              name: mysql-initdb

            - mountPath: "/var/lib/mysql/"
              # subpath: "mysql"
              name: mysql-pv-claim
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-configmap

        - name: mysql-pv-claim
          persistentVolumeClaim:
            claimName: mysql-pv-claim

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   labels:
#     app: db
# spec:
#   selector:
#     app: db
#   ports:
#     - port: 3306
#       targetPort: 3306
#       protocol: TCP
#   type: NodePort
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mysql
#   labels:
#     app: mysql
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#   serviceName: mysql
#   replicas: 2
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#         - name: mysql
#           image: mysql:latest
#           envFrom:
#             - configMapRef:
#                 name: auth-configmap
#             - secretRef:
#                 name: auth-secret
#           ports:
#             - containerPort: 3306
#               name: mp3-mysql
#           volumeMounts:
#             #  inside container
#             - mountPath: "/docker-entrypoint-initdb.d/"
#               name: mysql-initdb

#             - mountPath: "/var/lib/mysql/"
#               # subpath: "mysql"
#               name: mysql-persistent-storage
#       volumes:
#         - name: mysql-initdb
#           configMap:
#             name: mysql-initdb-configmap

#         - name: mysql-persistent-storage
#           persistentVolumeClaim:
#             claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  type: ClusterIP
  selector:
    app: mysql
    tier: database
  ports:
    - name: mp3-mysql
      protocol: TCP
      port: 3306
      targetPort: 3306

