---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: db
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secret
                key: MYSQL_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mp3-mysql
        volumeMounts:
            #  inside container
          - mountPath: /docker-entrypoint-initdb.d
            name: mysql-initdb
          - mountPath: "/var/lib/mysql"
            # subpath: "mysql"
            name: mysql-persistent-storage
      volumes:
        - name: mysql-initdb
          persistentVolumeClaim:
            claimName: mysql-initdb-pv-claim
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: NodePort


