apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{ PWD}/data"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-initdb-pv-claim
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{ PWD }/init.sql"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # - name: mysql-pv-claim
  #   labels:
  #     app: mysql
  name: mysql-initdb-pv-claim
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
