apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  # IP assigned to this service will only be accessible to 
  # this cluster
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
