# for less sensitive data
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-configmap
data:
  init.sql: |
    CREATE USER 'auth_user'@'mysql' IDENTIFIED BY 'Auth123';

    CREATE DATABASE auth;

    GRANT ALL PRIVILEGES ON auth.* TO 'auth_user'@'mysql';

    USE auth;

    CREATE TABLE user (
        id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL
    );

    INSERT INTO user (email, password) VALUES ('mikeyy@tokyo.com', 'Admin123');

